[tools]
air = "1.67.4"
go = "1.26.5"
node = "26"
pnpm = "11"

[tasks.dev]
usage = """
  arg "<file>" default="one.md"
"""
run = "air -- web --input ${usage_file}"

[tasks.fmt]
run = ["go fmt", "pnpm prettier -cw web/"]

[tasks.test]
run = "go test ./..."
