[tools]
air = "latest"
go = "latest"
node = "26"
pnpm = "latest"

[tasks.dev]
usage = """
  arg "<file>" default="one.md"
"""
run = "air -- web --input ${usage_file}"

[tasks.fmt]
run = ["go fmt", "pnpm prettier -cw web/"]

[tasks.test]
run = "go test ./..."
